export const data = [
  {
    id: "l-2",
    name: "Robe de Soirée ✨",
    slug: "",
    phone: "",
    price: "13900",
    delevery: "600",
    clr: ["Noir"],
    size: [40, 42, 44, 46, 48],
    descImag: "https://i.ibb.co/VW63C0QS/3.webp",
    themImg: "https://i.ibb.co/TD5w28zh/electroneque.webp",
  },
  {
    id: "l-3",
    name: "Ensemble Jupe ✨",
    slug: "",
    phone: "",
    price: "5900",
    delevery: "600",
    clr: ["Noir", "Beige", "Marron", "Rose", "Blanc", "Blue", "Rouge", "Vert"],
    size: [],
    descImag: "https://i.ibb.co/k2xvYghf/output.webp",
    themImg: "https://i.ibb.co/XZ2ncR10/1.png",
  },
  {
    id: "l-4",
    name: "✨ حجاب الأصالة",
    slug: "",
    phone: "",
    price: "5900",
    delevery: "600",
    clr: ["Noir", "Blanc"],
    size: [],
    descImag: "https://i.ibb.co/w9x52xP/output.webp",
    themImg:
      "https://i.ibb.co/kV5Hk1gb/Screenshot-from-2026-04-23-12-10-12.png",
  },
  {
    id: "l-5",
    name: "✨ جهاز قياس ضغط الدم ",
    slug: "",
    phone: "",
    price: "3800",
    delevery: "حسب الولاية",
    clr: [],
    size: [],
    descImag1: "https://i.ibb.co/6ckyW6vS/part-1.png",
    descImag2: "https://i.ibb.co/PzW35R67/part-2.png",
    descImag3: "https://i.ibb.co/5WXFhB62/part-3.png",
    themImg:
      "https://i.ibb.co/TBZVHpTt/Chat-GPT-Image-Apr-27-2026-02-31-20-PM.png",
    url: "https://script.google.com/macros/s/AKfycbz_J2x5pqjLilAGdQdNQpXuweYTxqRutNQtUyDiGc8QS5A9JrYsWc2civ5kznrsGnFzUg/exec",
  },
  {
    id: "l-6",
    name: "Robe Hijab ✨",
    slug: "",
    phone: "",
    price: "3900",
    delevery: "600",
    clr: ["Bleu Nuit", "Orange", "Marron"],
    size: [40, 42, 44, 46, 48],
    descImag1: "https://i.ibb.co/67P4mDg1/1-1.webp",

    themImg: "https://i.ibb.co/0pDz0nyQ/1.webp",
    url: "https://script.google.com/macros/s/AKfycbwTmWUg8PQsVio86mZT3GN9rJX7Bu1i5FEOhQX4XdCr7fWN5Caw16dDwUQV-8mxk4A6eg/exec",
  },
  {
    id: "l-7",
    name: "Ensemble Femme Élégant ✨",
    slug: "",
    phone: "",
    price: "2900",
    delevery: "600",
    clr: ["Beige", "Noir"],
    size: [36, 38, 40, 42, 44, 46],
    descImag1: "https://i.ibb.co/tMCGfVxN/22.webp",

    themImg: "https://i.ibb.co/Q7J8Fjr1/11.webp",
    url: "https://script.google.com/macros/s/AKfycbwTmWUg8PQsVio86mZT3GN9rJX7Bu1i5FEOhQX4XdCr7fWN5Caw16dDwUQV-8mxk4A6eg/exec",
  },
  {
    id: "l-8",
    name: "Ensemble Class & Élégant ✨",
    slug: "",
    phone: "",
    price: "4200",
    delevery: "600",
    clr: ["Rose", "Beige", "Vert", "Noir"],
    size: [40, 42, 44, 46, 48],
    descImag1: "https://i.ibb.co/MxvSFws0/output.webp",

    themImg: "https://i.ibb.co/gLkWpwx0/1.webp",
    url: "https://script.google.com/macros/s/AKfycbwTmWUg8PQsVio86mZT3GN9rJX7Bu1i5FEOhQX4XdCr7fWN5Caw16dDwUQV-8mxk4A6eg/exec",
  },
  {
    id: "l-9",
    name: "Robe D'ete En lin ✨",
    slug: "",
    phone: "",
    price: "3500",
    delevery: "600",
    clr: ["Vert", "Marron", "Bleu"],
    size: [36, 38, 40, 42, 44, 46],
    descImag1: "https://i.ibb.co/XfYVVg8J/output.webp",

    themImg: "https://i.ibb.co/pjRWqyRF/x.webp",
    url: "https://script.google.com/macros/s/AKfycbwTmWUg8PQsVio86mZT3GN9rJX7Bu1i5FEOhQX4XdCr7fWN5Caw16dDwUQV-8mxk4A6eg/exec",
  },
  {
    id: "l-10",
    name: "Robe Hijab ✨",
    slug: "",
    phone: "",
    price: "3900",
    delevery: "600",
    clr: ["Blanc", "Vert", "Bleu"],
    size: [38, 40, 42, 44, 46, 48],
    descImag1: "https://i.ibb.co/Z12DSP0G/output.webp",

    themImg: "https://i.ibb.co/DH58s8VW/1.webp",
    url: "https://script.google.com/macros/s/AKfycbwTmWUg8PQsVio86mZT3GN9rJX7Bu1i5FEOhQX4XdCr7fWN5Caw16dDwUQV-8mxk4A6eg/exec",
  },
];
