export const data = [
  {
    id: "l-2",
    name: "Robe de Soirée ✨",
    slug: "",
    phone: "",
    price: "13900",
    delevery: "600",
    clr: ["Noir"],
    size: [40, 42, 44, 46, 48],
    descImag: "https://i.ibb.co/VW63C0QS/3.webp",
    themImg: "https://i.ibb.co/TD5w28zh/electroneque.webp",
  },
  {
    id: "l-3",
    name: "Ensemble Jupe ✨",
    slug: "",
    phone: "",
    price: "5900",
    delevery: "600",
    clr: ["Noir", "Beige", "Marron", "Rose", "Blanc", "Blue", "Rouge", "Vert"],
    size: [],
    descImag: "https://i.ibb.co/k2xvYghf/output.webp",
    themImg: "https://i.ibb.co/XZ2ncR10/1.png",
  },
  {
    id: "l-4",
    name: "✨ حجاب الأصالة",
    slug: "",
    phone: "",
    price: "5900",
    delevery: "600",
    clr: ["Noir", "Blanc"],
    size: [],
    descImag: "https://i.ibb.co/w9x52xP/output.webp",
    themImg:
      "https://i.ibb.co/kV5Hk1gb/Screenshot-from-2026-04-23-12-10-12.png",
  },
  {
    id: "l-5",
    name: "✨ جهاز قياس ضغط الدم ",
    slug: "",
    phone: "",
    price: "4200",
    delevery: "حسب الولاية",
    clr: [],
    size: [],
    descImag1: "https://i.ibb.co/6ckyW6vS/part-1.png",
    descImag2: "https://i.ibb.co/PzW35R67/part-2.png",
    descImag3: "https://i.ibb.co/5WXFhB62/part-3.png",
    themImg:
      "https://i.ibb.co/TBZVHpTt/Chat-GPT-Image-Apr-27-2026-02-31-20-PM.png",
  },
];
